### PR TITLE
Handle race condition on upsert

### LINKED ISSUE #7: Improve upsert
The current implementation of upsert is vulnerable to a race condition if two jobs for the same entity are processed at the same time (`find_or_initialize_by` will "initialize" for both, but the second will fail because the primary key is not unique.

It should at least `retry` on `ActiveRecord::RecordNotUnique` errors; but better would be to use proper PostgreSQL upserts with https://github.com/jesjos/active_record_upsert (or our fork https://github.com/deliveroo/active_record_upsert which has a few additional features, until they get merged upstream).

### PR DESCRIPTION
**Pull request by mvalipour**
Closes #7 

@me @knaveofdiamonds

### CODE REVIEW

File: spec/materialist/materializer_spec.rb [hunk 1]
```diff
@@ -49,7 +49,14 @@ def actions_called
       end
 
       class << self
+        attr_accessor :error_to_throw_once_in_find_or_initialize_by
+
         def find_or_initialize_by(source_url:)
+          if(err = error_to_throw_once_in_find_or_initialize_by)
```
Comment (me) [inline spec/materialist/materializer_spec.rb]: I think the error would be thrown on `save`, not on `find_or_initialize_by`; but I guess it doesn't matter much here.

File: lib/materialist/materializer.rb [hunk 2]
```diff
@@ -76,10 +76,19 @@ def initialize(url, klass)
           @options = klass.materialist_options
         end
 
-        def upsert
+        def upsert(retry_on_race_condition: true)
```
Comment (me) [inline lib/materialist/materializer.rb]: What about an instance variable instead? That would avoid polluting the method arguments with an essentially private attribute.

File: spec/materialist/materializer_spec.rb (hunk 1 above)
Comment (mvalipour) [reply spec/materialist/materializer_spec.rb]: good point, although it doens't matter but I will follow for clarity

File: lib/materialist/materializer.rb (hunk 2 above)
Comment (mvalipour) [reply lib/materialist/materializer.rb]: It might make it a tad confusing given this parameter is used in the recursion logic :/

File: spec/materialist/materializer_spec.rb (hunk 1 above)
Comment (mvalipour) [reply spec/materialist/materializer_spec.rb]: OK, on a second thought it's not very trivial to do the same on `save!`, it's not ideal, but maybe we can keep this as it is?

Comment (me) [reply spec/materialist/materializer_spec.rb]: Sure no big deal I think 👍

File: lib/materialist/materializer.rb (hunk 2 above)
Comment (me) [reply lib/materialist/materializer.rb]: I see... Not a fan but ok!

Comment (knaveofdiamonds) [reply lib/materialist/materializer.rb]: I would also agree with retrying using `retry` + instance variable rather than recursion.
